"""Connect product specifications to specification library

Revision ID: 18425e8b3f60
Revises: df5286aa0d4c
Create Date: 2026-08-06 19:13:57.882543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18425e8b3f60'
down_revision = 'df5286aa0d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_specifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specification_library_id', sa.Integer(), nullable=False))
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_foreign_key(
            "fk_product_specifications_specification_library",
            "specification_library",
            ["specification_library_id"],
            ["id"],
        )        
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_specifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(
            "fk_product_specifications_specification_library",
            type_="foreignkey",
        )
        batch_op.alter_column('value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('specification_library_id')

    # ### end Alembic commands ###
