"""Support custom product specifications

Revision ID: 694bd983d277
Revises: 18425e8b3f60
Create Date: 2026-08-06 19:57:12.123285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694bd983d277'
down_revision = '18425e8b3f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_specifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_name', sa.String(length=120), nullable=True))
        batch_op.alter_column('specification_library_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_specifications', schema=None) as batch_op:
        batch_op.alter_column('specification_library_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('custom_name')

    # ### end Alembic commands ###
