"""Add alt text to product images

Revision ID: 975f50a13b3f
Revises: 0deef08a365a
Create Date: 2026-08-08 19:00:33.076111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975f50a13b3f'
down_revision = '0deef08a365a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_gallery')
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alt_text', sa.String(length=255), nullable=True))
        batch_op.alter_column('is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('display_order',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.alter_column('display_order',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('alt_text')

    op.create_table('product_gallery',
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('alt_text', sa.VARCHAR(length=255), nullable=True),
    sa.Column('display_order', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
