"""Create specification library

Revision ID: d91d87fa1633
Revises: cbc218d3e2ea
Create Date: 2026-08-01 19:33:59.219989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91d87fa1633'
down_revision = 'cbc218d3e2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specification_library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_type', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('unit', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('is_required', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_filterable', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specification_library', schema=None) as batch_op:
        batch_op.drop_column('is_filterable')
        batch_op.drop_column('is_required')
        batch_op.drop_column('unit')
        batch_op.drop_column('data_type')

    # ### end Alembic commands ###
